export enum TILE_TYPE_ENUM {
  WALL_LEFT_TOP = 'WALL_LEFT_TOP',
  WALL_COLUMN = 'WALL_COLUMN',
  WALL_LEFT_BOTTOM = 'WALL_LEFT_BOTTOM',
  CLIFF_LEFT = 'CLIFF_LEFT',
  WALL_RIGHT_BOTTOM = 'WALL_RIGHT_BOTTOM',
  FLOOR = 'FLOOR',
  CLIFF_CENTER = 'CLIFF_CENTER',
  WALL_ROW = 'WALL_ROW',
  WALL_RIGHT_TOP = 'WALL_RIGHT_TOP',
  CLIFF_RIGHT = 'CLIFF_RIGHT',
}

